### ISSUE TITLE
Persistence failure when replaying events for persistenceId

### ISSUE THREAD

**Issue by harmeetsingh0013** [ironfish/akka-persistence-mongo#106]
I am uisng akka-persistence with mongodb but after running my code, i am getting following error: 
`[ERROR] [11/19/2016 16:47:29.355] [transaction-system-akka.actor.default-dispatcher-5] [akka://transaction-system/user/$a] Persistence failure when replaying events for persistenceId [balanceTransactions]. Last known sequence number [0] (akka.persistence.RecoveryTimedOut)`

[For more details, please click](http://stackoverflow.com/questions/40692372/akka-persistence-and-mongodb-persistence-failure-when-replaying-events-for-pers)

**Comment by synox** [comment]
It seems that you solved it in http://stackoverflow.com/a/40693580/79461 ?

**Comment by harmeetsingh0013** [comment]
Hey @synox, yes thanks my issue was resolve, I apologise for update here. I will close the issue.
