### ISSUE TITLE
CasbahJournal actor fail with PostRestartException and stay dead forever

### ISSUE THREAD

**Issue by haghard** [ironfish/akka-persistence-mongo#74]
When db become unavailable akka will try recreate CasbahJournal actor and this operation failed with PostRestartException. The reason is CasbahJournalHelper lines (47,48,49). Maybe we need to find more suitable place for this operations

**Comment by haghard** [comment]
No, it hasn't. https://github.com/ironfish/akka-persistence-mongo/pull/89

**Comment by ironfish** [comment]
Fixed #89
