### ISSUE TITLE
processorId to persistenceId

### ISSUE THREAD

**Issue by michaelHampel** [ironfish/akka-persistence-mongo#77]
Hello,

in the last versions processorId was renamed to persistenceId in the bson document.
Therefore all the events we already persisted before upgrading to the new version could not be read anymore. We could work around it, but it would be nice if there would be a warning in the documentation about it.
For the future - is it possible to name this key independent from how it is called in akka persistence - smthg. like pid?

thanks,

michael

**Comment by ironfish** [comment]
@michaelHampel, I going to close this issues if that's okay with you. As I ramp up for Akka 2.4 there will be other changes as well and for now most everyone is set on persistenceId.
