### ISSUE TITLE
why only 30/s persistent performance

### ISSUE THREAD

**Issue by snailwxy** [ironfish/akka-persistence-mongo#82]
Hello,
I'm testing the akka-sample-persistence-java in typesafe, but get only 30 persistent messages per second and I think I must get something wrong.

here is my build.sbt file, 
name := """akka-sample-persistence-java"""
version := "2.3.5"
scalaVersion := "2.10.4"
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/releases"
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"	
libraryDependencies ++= Seq(
  "com.github.ddevore" %% "akka-persistence-mongo-casbah"  % "0.7.4" % "compile",
  "com.typesafe.akka" %% "akka-persistence-experimental" % "2.3.5",
  "com.github.ironfish" %% "akka-persistence-mongo-casbah"  % "0.7.5-SNAPSHOT" % "compile"
)

And my application.conf is,
akka.persistence.journal.plugin = "casbah-journal"
casbah-journal.mongo-journal-url = "mongodb://localhost:27017/store.messages"
akka.persistence.snapshot-store.plugin = "casbah-snapshot-store"
casbah-snapshot-store.mongo-snapshot-url = "mongodb://localhost:27017/store.snapshots"

my mongodb is 2.4.12, and I just use command "mongod" to start the default mongo. And my test code is,
public static void main(String... args) throws Exception {
        final ActorSystem system = ActorSystem.create("example");
        final ActorRef persistentActor = 
            system.actorOf(Props.create(ExamplePersistentActor.class), "persistentActor-4-java");

	for(int i = 0;i < 100000; i++){
		persistentActor.tell(new Cmd("a"), null);	
	}        
        Thread.sleep(60000);
        system.shutdown();
    }

when i run with cassadra with the same code, i can persist about 3000 messages per second, but only 30 with mongodb.

**Comment by marcuslinke** [comment]
Hi, i'm experiencing the very same problem with 0.7.4 and mongo 2.4.10. Are there any solutions/ hints?

**Comment by snailwxy** [comment]
hi, @marcuslinke 
when I call the interface "persist()", I still get a very low performance. But “persistSync()” can be about 6K/s.

**Comment by marcuslinke** [comment]
@snailwxy Thanks! That saved my day!

**Comment by ironfish** [comment]
Make sure `mongo-journal-write-concern` = "journaled" when using `persistAsync`.

@snailwxy - If your satisfied, can you go ahead and close this issue?

Thanks,
