### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by nloyola** [ironfish/akka-persistence-mongo#92]
I'm using Play 2.4.0 with akka-persistence-experimental (2.3.9) and akka-persistence-mongo-casbah (0.7.5) for storage. After upgrading to Play 2.4.0, I have an issue with my test suites and the number of connection to my mongo server. I get a 

* `com.mongodb.MongoException$Network`

I'm also using [scalatestplus-play](https://github.com/scalatest/scalatestplus-play) and have each test suite configured to start a new play application on each test. From the log messages I can see that Akka is being shut down after each test. I also have a mongo shell open and can see that there are no available connections (using the `db.serverStatus().connections` command).

I never had this issue when I was using Play 2.3.x.

How can I fix this problem?

Thanks

**Comment by nloyola** [comment]
A few weeks ago I upgraded to Ubuntu 15.04 and that left me with a bad version of mongodb installed. Once I installed a valid one everything works again and I do not run into this problem.

Please disregard this issue.

**Comment by ironfish** [comment]
Glad to see this is resolved.
