### ISSUE TITLE
Akka 2.4.x support

### ISSUE THREAD

**Issue by ironfish** [ironfish/akka-persistence-mongo#99]

**Comment by manuelbernhardt** [comment]
@ironfish do you have any idea how much work this update is? I am thinking it would make sense to have a 2.4.x version in https://github.com/manuelbernhardt/reactive-web-applications/tree/master/CH07 and could perhaps contribute

**Comment by ironfish** [comment]
It's something I am looking over now, and a priority. I'm looking to do the upgrade over the next two weeks.

**Comment by manuelbernhardt** [comment]
@ironfish do you have an idea when you will be able to work on this upgrade? I am getting closer to wrapping up the book & code examples and it would be nice to be able to use a more recent version in the examples

**Comment by ironfish** [comment]
@manuelbernhardt I'm working on it now. In addition to `Akka 2.4` it will also include the new `async` driver.

**Comment by ironfish** [comment]
@manuelbernhardt I've finished the changes for `Akka 2.4.1`. I will push in the next day or so after I have added additional tests.

Cheers,

**Comment by ironfish** [comment]
@manuelbernhardt I have merged the `Akka 2.4.1.` and published to [snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/github/ironfish/akka-persistence-mongo_2.11/). Make sure you review the [README](https://github.com/ironfish/akka-persistence-mongo) as there are some changes around configuration you should be aware of.

**Comment by manuelbernhardt** [comment]
@ironfish thanks! I will upgrade the chapter in the coming days with it

**Comment by ironfish** [comment]
fixed by #100
